trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  projectPath: './NetCore3.1TestApplication/NetCore3.1TestApplication/NetCore3.1TestApplication.csproj'
  libraryPath: './NetCore3.1TestApplication/NetCore3.1TestLibrary/NetCore3.1TestLibrary.csproj'
  efToolVersion: '3.1.0'
  netSdkVersion: '3.1.100'

steps:

- task: UseDotNet@2
  displayName: 'Use .Net Core sdk $(netSdkVersion)'
  inputs:
    version: $(netSdkVersion)

- script: 'dotnet restore $(projectPath)'
  displayName: Restore

- script: 'dotnet build $(projectPath) --configuration $(buildConfiguration)'
  displayName: Build

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate migrations scripts - Library project'
  inputs:
    projectpath: $(libraryPath)
    databasecontexts: |
     LibraryDatabaseContext
     InternalLibraryDatabaseContext
    startupprojectpath: $(projectPath)
    installdependencies: true
    eftoolversion: '$(efToolVersion)'

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate migrations scripts - Main project'
  inputs:
    projectpath: $(projectPath)
    databasecontexts: FirstDatabaseContext
    installdependencies: false

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate migrations scripts - All in one'
  inputs:
    projectpath: $(projectPath)
    databasecontexts: |
     FirstDatabaseContext
     SecondDatabaseContext
     LibraryDatabaseContext
     InternalLibraryDatabaseContext
    installdependencies: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'

